## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import gmaps
import gmaps.datasets
import requests

# Import the API key.
from config_g import gkey

In [3]:
# Configure gmaps API key
gmaps.configure(api_key=gkey)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Avarua,CK,-21.21,-159.78,71.60,88,100,9.17,overcast clouds,2020-09-05 17:01:45
1,1,Port Alfred,ZA,-33.59,26.89,63.64,74,84,9.78,broken clouds,2020-09-05 17:01:45
2,2,Busselton,AU,-33.65,115.33,63.00,71,79,20.38,broken clouds,2020-09-05 17:01:45
3,3,Mackenzie,CA,55.30,-123.17,53.60,93,75,2.24,broken clouds,2020-09-05 17:01:45
4,4,Atuona,PF,-9.80,-139.03,79.48,73,15,21.88,few clouds,2020-09-05 17:01:46

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

# 6.5.3 Get Vacation Criteria
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

# 6.5.3 Get Vacation Criteria

# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Avarua,CK,-21.21,-159.78,71.60,88,100,9.17,overcast clouds,2020-09-05 17:01:45
4,4,Atuona,PF,-9.80,-139.03,79.48,73,15,21.88,few clouds,2020-09-05 17:01:46
6,6,Sochi,RU,43.60,39.73,77.00,83,90,2.24,light rain,2020-09-05 17:01:34
7,7,Bethel,US,41.37,-73.41,75.99,35,1,9.17,clear sky,2020-09-05 17:01:46
10,10,Kapaa,US,22.08,-159.32,78.80,74,20,13.87,few clouds,2020-09-05 17:01:20
12,12,Naliya,IN,23.27,68.83,83.07,78,0,10.02,clear sky,2020-09-05 17:01:47
13,13,Dawlatabad,AF,36.41,64.91,74.46,20,0,4.07,clear sky,2020-09-05 17:01:48
14,14,Jurado,CO,7.11,-77.76,84.00,70,47,6.91,light rain,2020-09-05 17:01:48
15,15,Gisenyi,RW,-1.70,29.26,71.80,55,60,0.92,broken clouds,2020-09-05 17:00:58
18,18,Albany,US,42.60,-73.97,75.00,35,0,1.01,clear sky,2020-09-05 17:00:40

In [7]:
# 4a. Determine if there are any empty rows.
# 6.5.3 Get Vacation Criteria
#check for null
preferred_cities_df.isnull().sum().sum()

3

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.isnull().sum().sum()

0

In [9]:
# Original row count
len(city_data_df.index)

713

In [10]:
# Filtered to temp preference inputs
len(preferred_cities_df.index)

356

In [11]:
# Filtered to remove NaN
len(clean_df)

353

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp Current Description    Lat     Lng Hotel Name
0       Avarua      CK     71.60     overcast clouds -21.21 -159.78
4       Atuona      PF     79.48          few clouds  -9.80 -139.03
6        Sochi      RU     77.00          light rain  43.60   39.73
7       Bethel      US     75.99           clear sky  41.37  -73.41
10       Kapaa      US     78.80          few clouds  22.08 -159.32
12      Naliya      IN     83.07           clear sky  23.27   68.83
13  Dawlatabad      AF     74.46           clear sky  36.41   64.91
14      Jurado      CO     84.00          light rain   7.11  -77.76
15     Gisenyi      RW     71.80       broken clouds  -1.70   29.26
18      Albany      US     75.00           clear sky  42.60  -73.97

In [13]:
## TEST
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

lat = -21.21
lng = -159.78
params["location"] = f"{lat},{lng}"
params

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

hotels = requests.get(base_url, params=params).json()
hotels

{'html_attributions': [],
 'next_page_token': 'CqQCHwEAAGziGtSpOnqEGWypyy9bBjqUT66LtvYf6L0csv0UXW_tUUaBFJSNGBAv4Jue_ofPujbn_UL7vQNTsKgVZaJEPJBcSFRBmMhPefMhijaCMCnOxVl4m4Lng3QpAH4DYZ_HNSd3VRGEHUXisRN-BFAKmIbHAt2zeCpivMQY8-_0gk5_H2RjMW9a1hh66MufUe4Nx-DvOmEe8X2BtVw4nrPNUZLqSXNQ1H44tBgF4kS3p5kNhHg2gMi2DHEMD9pBwBvNM9_sq68iEvBD105vLirS-fLopvQNp9tLkBZ8QbZ9T15Rw29660AVpjeDwRSl1NrsWax5Fj6DwUQWL9on7PvmWrBlQbilFRRLOqTouhVwnxxgfy3vmObxDipJFYKBtqfOzRIQw8C6Lz6xkjpHktznYwF7yRoUeS0WHBmWYsXRMga5qq1YxqUm65Y',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.205333, 'lng': -159.769621},
    'viewport': {'northeast': {'lat': -21.2040737197085,
      'lng': -159.7682612697085},
     'southwest': {'lat': -21.2067716802915, 'lng': -159.7709592302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Paradise Inn',
   'photos': [{'height': 2304,
     'html_attributions': ['From a Google User'],
     'photo_reference': 'CkQ0AAAAm1JdrDioSy09maoCiYzgAYkZytCbboAfFBja-UJhMhc-g_ZZlefdagydOl33IHs6n_yJXp8hLm2igBZiHxMfthIQrM8c1QJBg76QRXM0Zqtv4xoUxDaTqr87Z614fFI5Oi214a3iRYA',
     'width': 3072}],
   'place_id': 'ChIJ9QiApYjRV3ER23zG7_ZaAF0',
   'plus_code': {'compound_code': 'Q6VJ+V5 Avarua District, Cook Islands',
    'global_code': '53C2Q6VJ+V5'},
   'rating': 3.9,
   'reference': 'ChIJ9QiApYjRV3ER23zG7_ZaAF0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 9,
   'vicinity': 'Ara Tapu, Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.21311, 'lng': -159.82602},
    'viewport': {'northeast': {'lat': -21.21176186970849,
      'lng': -159.8246697197085},
     'southwest': {'lat': -21.2144598302915, 'lng': -159.8273676802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Sunset Resort',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113054221025676311269">Robert W</a>'],
     'photo_reference': 'CkQ0AAAAKyLvOwcaVHeUQ17SUkNXJxo91m2CHudGMDyxISwdQXeubA2m4kSvXt0XkYceLW1V_OVFwZElISg-I-bsgrah6hIQ6QaKfVTVYeBL9ucfQ55c4xoUvlLvH4tXKpaiPa2td6I_S_f-CdY',
     'width': 4032}],
   'place_id': 'ChIJt5zh1FrQV3ERed-JUjP4SO0',
   'plus_code': {'compound_code': 'Q5PF+QH Arorangi District, Cook Islands',
    'global_code': '53C2Q5PF+QH'},
   'rating': 4.5,
   'reference': 'ChIJt5zh1FrQV3ERed-JUjP4SO0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 102,
   'vicinity': 'Ara Tapu, Arorangi Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2037416, 'lng': -159.7548332},
    'viewport': {'northeast': {'lat': -21.2025916197085,
      'lng': -159.7535594197085},
     'southwest': {'lat': -21.2052895802915, 'lng': -159.7562573802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Club Raro Resort',
   'photos': [{'height': 4128,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111427930198428936711">Soni E</a>'],
     'photo_reference': 'CkQ0AAAAdHDK4NS8LOyzlTPCBDwPBun4Dxaqh0_3DzxecCYIx-i5vSqzIWmCkzUojaTNe4ZM3aNWazDGCC0uwzhqCjkzrBIQJoiNLF3x3RdSamsfq3K6cBoUKb0KlzycN2_w3PjBOlZEKGJ5fmY',
     'width': 3096}],
   'place_id': 'ChIJ1zZCmbbRV3ERxrdPE8eKN1k',
   'plus_code': {'compound_code': 'Q6WW+G3 Avarua District, Cook Islands',
    'global_code': '53C2Q6WW+G3'},
   'rating': 3.8,
   'reference': 'ChIJ1zZCmbbRV3ERxrdPE8eKN1k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 116,
   'vicinity': '483 Avarua Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.204566, 'lng': -159.7522},
    'viewport': {'northeast': {'lat': -21.2033293697085,
      'lng': -159.7509076197085},
     'southwest': {'lat': -21.2060273302915, 'lng': -159.7536055802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Kiikii Inn & Suites - Rarotonga',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1536,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100680853646633201105">Kiikii Inn &amp; Suites - Rarotonga</a>'],
     'photo_reference': 'CkQ0AAAAsQgptsFyI-OX6wSC94jJ_g6k-5E3i-rvbbtJ8cP7OX7dB5YH37foPxd1HJqvSsWoYtFuT-ixpRy7qgap8et2uxIQo4UEKicocmPWfMAxZYTXkBoU25WdvldTXC5OetDByoPvQOJuhnc',
     'width': 2730}],
   'place_id': 'ChIJJ-8mSbrTV3ERWSX_ApWf-uA',
   'plus_code': {'compound_code': 'Q6WX+54 Avarua District, Cook Islands',
    'global_code': '53C2Q6WX+54'},
   'rating': 3.5,
   'reference': 'ChIJJ-8mSbrTV3ERWSX_ApWf-uA',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 12,
   'vicinity': 'Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.208599, 'lng': -159.7899199},
    'viewport': {'northeast': {'lat': -21.2070859197085,
      'lng': -159.7886178197085},
     'southwest': {'lat': -21.2097838802915, 'lng': -159.7913157802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Atupa Orchid Units',
   'place_id': 'ChIJS-ChyaLRV3ERdkq2vYaWPz0',
   'plus_code': {'compound_code': 'Q6R6+H2 Avarua District, Cook Islands',
    'global_code': '53C2Q6R6+H2'},
   'rating': 4.5,
   'reference': 'ChIJS-ChyaLRV3ERdkq2vYaWPz0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2,
   'vicinity': 'P.O. Box 64, Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.1991091, 'lng': -159.7953621},
    'viewport': {'northeast': {'lat': -21.1979112697085,
      'lng': -159.7940298697085},
     'southwest': {'lat': -21.2006092302915, 'lng': -159.7967278302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'The Islander Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 770,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116182363482589837891">The Islander Hotel</a>'],
     'photo_reference': 'CkQ0AAAAKUismXbEam5-FkSQMPNOD0Qqw1qDUwoARm3QEqP-Hc5LqDRNvePIotX4PU8jmetPcwpCrq2bqmUU3H-7kXpKRBIQmfbJcIz1VyIlpgkmCOXLChoUx7YYnAlQUNuwAcpXlm2dFofT5-A',
     'width': 1368}],
   'place_id': 'ChIJmVoxwbjRV3ERXkJfFo6QLjY',
   'plus_code': {'compound_code': 'R623+9V Avarua District, Cook Islands',
    'global_code': '53C2R623+9V'},
   'rating': 4,
   'reference': 'ChIJmVoxwbjRV3ERXkJfFo6QLjY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 109,
   'vicinity': 'Ara Tapu Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2082764, 'lng': -159.7796364},
    'viewport': {'northeast': {'lat': -21.2069505697085,
      'lng': -159.7781894197085},
     'southwest': {'lat': -21.20964853029151, 'lng': -159.7808873802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Wellesley Hotel Rarotonga',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 747,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115141323948637255443">Wellesley Hotel Rarotonga</a>'],
     'photo_reference': 'CkQ0AAAAcj7R1Gp4GNFNkQJ5QH4e1ltfdVVHeUfEruR3Vquh6QHVwSUSl1cczDrvhPHUoUMOkyOEth0o-WBowXdVZ7ZRXRIQKgJVc7yvs80HjREAU5WIbBoUqVvi_ywSx1-XoXok2sDUP_xU63Y',
     'width': 747}],
   'place_id': 'ChIJy9R-WZrRV3ER8VgoTdHCesQ',
   'plus_code': {'compound_code': 'Q6RC+M4 Avarua District, Cook Islands',
    'global_code': '53C2Q6RC+M4'},
   'rating': 4.1,
   'reference': 'ChIJy9R-WZrRV3ER8VgoTdHCesQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 7,
   'vicinity': 'Corner Puoromea Road and Vakatini Road, Tutakimoa Rarotonga, Avarua District, Vakatini Rd, Avarua District, Cook Islands Vakatini Road Avarua'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.208484, 'lng': -159.7752267},
    'viewport': {'northeast': {'lat': -21.2071465197085,
      'lng': -159.7740076197085},
     'southwest': {'lat': -21.2098444802915, 'lng': -159.7767055802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Central Motel',
   'photos': [{'height': 2208,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115247569870955350839">あな</a>'],
     'photo_reference': 'CkQ0AAAAvaa3qnwr2FtOh-nP9qk_vAW4I0DwJLMrwStdawuyWAXl1wWLDXrMd51ehkMWJO5YbreqjIhUadewwi6e0sUetBIQRmVfZELe-C3paYfYS-bO6xoUkwKL91cUwYbfSd5R6JKo_FiG1sU',
     'width': 3928}],
   'place_id': 'ChIJa-dVI4XRV3ERSWduWUoHVOU',
   'plus_code': {'compound_code': 'Q6RF+JW Avarua District, Cook Islands',
    'global_code': '53C2Q6RF+JW'},
   'rating': 3.5,
   'reference': 'ChIJa-dVI4XRV3ERSWduWUoHVOU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4,
   'vicinity': 'Takuvaine Road, Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2060107, 'lng': -159.7500433},
    'viewport': {'northeast': {'lat': -21.2046837697085,
      'lng': -159.7487117197085},
     'southwest': {'lat': -21.2073817302915, 'lng': -159.7514096802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Kiikii Beach House - Raro Holiday Homes',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104349646020805962204">Brian Bourgault</a>'],
     'photo_reference': 'CkQ0AAAAs_Q4_53r0F33D4yfJcSWBKK3V6T6wy_mV62MGGxGqn8JC_h6_uIv0mQ7ea96PNr8SK8wC3BWdZaGari-s6n9axIQuR2kgRCz07SaggMAwd8tjxoUY8nIvc6MqdGFyZnbUl4_jaRBZwQ',
     'width': 4032}],
   'place_id': 'ChIJr6oxUzDSV3ERJzoFBVIWlj4',
   'plus_code': {'compound_code': 'Q6VX+HX Avarua District, Cook Islands',
    'global_code': '53C2Q6VX+HX'},
   'rating': 3.3,
   'reference': 'ChIJr6oxUzDSV3ERJzoFBVIWlj4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 3,
   'vicinity': 'Ara Tapu, Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2066628, 'lng': -159.7525542},
    'viewport': {'northeast': {'lat': -21.20488281970849,
      'lng': -159.7517053697085},
     'southwest': {'lat': -21.2075807802915, 'lng': -159.7544033302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
   'name': "GT's - Rarotonga Fishing Lodge",
   'photos': [{'height': 3456,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117865350999269406613">GT&#39;s - Rarotonga Fishing Lodge</a>'],
     'photo_reference': 'CkQ0AAAAj5OlJhJPEJQRqa3evpGvCS6hdwG99eyx3xQbAxerX-3K7lcNHLmuUF_WXHKpd4yuhNOKP2qwIwI6r_Aj2QKmmxIQyP_REX48sqUXdKyB7xEnwhoUydgDlLytBJ6V3QlzFZACrySi0V4',
     'width': 5184}],
   'place_id': 'ChIJv3Ny1jHSV3ERdLBEanPYg0o',
   'plus_code': {'compound_code': 'Q6VW+8X Avarua District, Cook Islands',
    'global_code': '53C2Q6VW+8X'},
   'rating': 5,
   'reference': 'ChIJv3Ny1jHSV3ERdLBEanPYg0o',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2,
   'vicinity': 'Tupapa, Rarotonga, Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2275106, 'lng': -159.8197604},
    'viewport': {'northeast': {'lat': -21.2261514697085,
      'lng': -159.8184084697085},
     'southwest': {'lat': -21.2288494302915, 'lng': -159.8211064302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Iro Luxury Retreat',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100636687170160350571">hamlin flat</a>'],
     'photo_reference': 'CkQ0AAAA9zFfwtwkCMBZzmwtOMfDzU8cIL89kFqddxcRZclY2KyVw-BY8Sj0ve0ICkYCLxaGu6TP8DnkQLixdqA9ez8HghIQ7szrYnLAo5J0icewCltDTBoUG1Tj9kinRZXzZ09BPqZ7F0FlIF0',
     'width': 4032}],
   'place_id': 'ChIJ187SFPnQV3ER75nwEDUhTkc',
   'plus_code': {'compound_code': 'Q5CJ+X3 Arorangi District, Cook Islands',
    'global_code': '53C2Q5CJ+X3'},
   'rating': 4.6,
   'reference': 'ChIJ187SFPnQV3ER75nwEDUhTkc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 7,
   'vicinity': 'Arerenga Road, Arorangi District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2109519, 'lng': -159.8253748},
    'viewport': {'northeast': {'lat': -21.2097081697085,
      'lng': -159.8237168197085},
     'southwest': {'lat': -21.2124061302915, 'lng': -159.8264147802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Blue Lagoon Villa',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106309197497520079159">Arun Kumar</a>'],
     'photo_reference': 'CkQ0AAAAMKUe7G7XomjRQqLuqfV_Jq5wmbkVhQY8AgxwZbTu6l-4pRrw94IMg1kfyomt-UrsL6ySOjWf8EiB6JIGpQkJ_hIQFSNp-hQoU465MEcUeTznJhoUYDNyutsXcK03YKvfrawHprY2mHc',
     'width': 3024}],
   'place_id': 'ChIJjwHiakXQV3ERPPsCRE18qTk',
   'plus_code': {'compound_code': 'Q5QF+JV Arorangi District, Cook Islands',
    'global_code': '53C2Q5QF+JV'},
   'rating': 5,
   'reference': 'ChIJjwHiakXQV3ERPPsCRE18qTk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4,
   'vicinity': 'Arorangi District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2124189, 'lng': -159.8263299},
    'viewport': {'northeast': {'lat': -21.2112545697085,
      'lng': -159.8246851697085},
     'southwest': {'lat': -21.2139525302915, 'lng': -159.8273831302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'The Cooks Oasis Holiday Villas',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1367,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112849541936146946492">Adele de Beer</a>'],
     'photo_reference': 'CkQ0AAAAOXBfxmd9MchrAO8p0DPFn2LJC3WrVZesn8bw2Oc9RvtmjpmT5zMG92OM57zHAQ9Vxrkw0Q6F1tsJeLfoiMZ70BIQVuqj2OjhXbicz92x81H0JxoUMNaZuGXxc5kjn6OsalXZq4R7-Ls',
     'width': 2048}],
   'place_id': 'ChIJb5-_LUXQV3ER48tMjvhaETU',
   'plus_code': {'compound_code': 'Q5QF+2F Arorangi District, Cook Islands',
    'global_code': '53C2Q5QF+2F'},
   'rating': 4.6,
   'reference': 'ChIJb5-_LUXQV3ER48tMjvhaETU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 12,
   'vicinity': 'Main Road Rarotonga'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.213154, 'lng': -159.827106},
    'viewport': {'northeast': {'lat': -21.2120592697085,
      'lng': -159.8253995697085},
     'southwest': {'lat': -21.2147572302915, 'lng': -159.8280975302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Onu Bay Holiday House',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113621299210036581725">Onu Bay Holiday House</a>'],
     'photo_reference': 'CkQ0AAAAmAf-dO1GcjcRJsWZqR-adk_qcib0SzAA9cYfwDCRE-Aal4e104celdddimQ_Xl3S6cPuycYquosycZT6hLkV3hIQDHz8lpCfmNcfRuBe8slsNxoUEgm_-VTKiKmF4xQLyijSJbzYj9o',
     'width': 4032}],
   'place_id': 'ChIJA65YzF7QV3ERI1cOBxPeVg0',
   'plus_code': {'compound_code': 'Q5PF+P5 Arorangi District, Cook Islands',
    'global_code': '53C2Q5PF+P5'},
   'rating': 4.8,
   'reference': 'ChIJA65YzF7QV3ERI1cOBxPeVg0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 6,
   'vicinity': 'Ara Tapu, Arorangi District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.211277, 'lng': -159.780345},
    'viewport': {'northeast': {'lat': -21.2100325197085, 'lng': -159.7777473},
     'southwest': {'lat': -21.2127304802915, 'lng': -159.7812109}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Avarua Heights',
   'place_id': 'ChIJj8kilpvRV3ERjAhKh5sEhGE',
   'plus_code': {'compound_code': 'Q6Q9+FV Arorangi District, Cook Islands',
    'global_code': '53C2Q6Q9+FV'},
   'reference': 'ChIJj8kilpvRV3ERjAhKh5sEhGE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '21°12\'40.6"S 159°46\'49., Akaoa No. 2 Road, Arorangi District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2061384, 'lng': -159.7777191},
    'viewport': {'northeast': {'lat': -21.2047891697085,
      'lng': -159.7761727197085},
     'southwest': {'lat': -21.2074871302915, 'lng': -159.7788706802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Lazy Trout',
   'opening_hours': {'open_now': True},
   'place_id': 'ChIJTU_4FjzRV3ER1hQ3krXCmHE',
   'plus_code': {'compound_code': 'Q6VC+GW Avarua District, Cook Islands',
    'global_code': '53C2Q6VC+GW'},
   'reference': 'ChIJTU_4FjzRV3ER1hQ3krXCmHE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.209232, 'lng': -159.7721},
    'viewport': {'northeast': {'lat': -21.2078830197085,
      'lng': -159.7707510197085},
     'southwest': {'lat': -21.21058098029151, 'lng': -159.7734489802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Rarotonga GolfSeaview',
   'place_id': 'ChIJX9IMSYTRV3ERJMtURuoJGsM',
   'plus_code': {'compound_code': 'Q6RH+85 Avarua District, Cook Islands',
    'global_code': '53C2Q6RH+85'},
   'reference': 'ChIJX9IMSYTRV3ERJMtURuoJGsM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Ara Metua Road, Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2067636, 'lng': -159.7873959},
    'viewport': {'northeast': {'lat': -21.2054900697085,
      'lng': -159.7859344197085},
     'southwest': {'lat': -21.2081880302915, 'lng': -159.7886323802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Herangis Retreat',
   'photos': [{'height': 312,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104895983603046498346">Timoti Tangiruaine</a>'],
     'photo_reference': 'CkQ0AAAAgpcYWawtykg5teUZ1cvV1nE4X0cO9RysLPg6cGtKc0nSP8aFDubvssIdISYD9HMVfLAbxNkVlOJOil5JO1WnyxIQQ4rCkTx2NlUFuIlrFUJFmhoUboatgAQ0tOoM0WdFKCN5VBie1Xo',
     'width': 589}],
   'place_id': 'ChIJU_PM6JfRV3ERPXzTrANcCDo',
   'plus_code': {'compound_code': 'Q6V7+72 Avarua District, Cook Islands',
    'global_code': '53C2Q6V7+72'},
   'reference': 'ChIJU_PM6JfRV3ERPXzTrANcCDo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Avatiu Road, Avarua District'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -21.2096673, 'lng': -159.7697401},
    'viewport': {'northeast': {'lat': -21.2083173697085,
      'lng': -159.7684248697085},
     'southwest': {'lat': -21.21101533029151, 'lng': -159.7711228302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'name': 'Nuki Rd',
   'place_id': 'ChIJ26DAmYbRV3ERhz4MBvSBAO0',
   'plus_code': {'compound_code': 'Q6RJ+44 Avarua District, Cook Islands',
    'global_code': '53C2Q6RJ+44'},
   'reference': 'ChIJ26DAmYbRV3ERhz4MBvSBAO0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

# 6b. Iterate through the hotel DataFrame.
ExceptCount = 0

# 6.5.4 Map Vacation Criteria
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # 6c. Get latitude and longitude from DataFrame
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        ExceptCount = ExceptCount + 1

print(ExceptCount)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
28

In [15]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Avarua,CK,71.60,overcast clouds,-21.21,-159.78,Paradise Inn
4,Atuona,PF,79.48,few clouds,-9.80,-139.03,Villa Enata
6,Sochi,RU,77.00,light rain,43.60,39.73,Bounty Hotel
7,Bethel,US,75.99,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
10,Kapaa,US,78.80,few clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
12,Naliya,IN,83.07,clear sky,23.27,68.83,Hotel Panchvati
13,Dawlatabad,AF,74.46,clear sky,36.41,64.91,WASIM ASGAR KHAN
14,Jurado,CO,84.00,light rain,7.11,-77.76,
15,Gisenyi,RW,71.80,broken clouds,-1.70,29.26,Palm garden Resort
18,Albany,US,75.00,clear sky,42.60,-73.97,

In [16]:
# 7. Drop the rows where there is no Hotel Name.

import numpy as np
# replace field that's entirely space (or empty) with NaN
clean_hotel_df = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Avarua,CK,71.60,overcast clouds,-21.21,-159.78,Paradise Inn
4,Atuona,PF,79.48,few clouds,-9.80,-139.03,Villa Enata
6,Sochi,RU,77.00,light rain,43.60,39.73,Bounty Hotel
7,Bethel,US,75.99,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
10,Kapaa,US,78.80,few clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
12,Naliya,IN,83.07,clear sky,23.27,68.83,Hotel Panchvati
13,Dawlatabad,AF,74.46,clear sky,36.41,64.91,WASIM ASGAR KHAN
14,Jurado,CO,84.00,light rain,7.11,-77.76,NaN
15,Gisenyi,RW,71.80,broken clouds,-1.70,29.26,Palm garden Resort
18,Albany,US,75.00,clear sky,42.60,-73.97,NaN

In [17]:
# 7. Drop the rows where there is no Hotel Name.
new_hotel_df = clean_hotel_df.dropna(axis=0,how='any')
new_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Avarua,CK,71.60,overcast clouds,-21.21,-159.78,Paradise Inn
4,Atuona,PF,79.48,few clouds,-9.80,-139.03,Villa Enata
6,Sochi,RU,77.00,light rain,43.60,39.73,Bounty Hotel
7,Bethel,US,75.99,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
10,Kapaa,US,78.80,few clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
12,Naliya,IN,83.07,clear sky,23.27,68.83,Hotel Panchvati
13,Dawlatabad,AF,74.46,clear sky,36.41,64.91,WASIM ASGAR KHAN
15,Gisenyi,RW,71.80,broken clouds,-1.70,29.26,Palm garden Resort
20,Tateyama,JP,80.01,light rain,34.98,139.87,Tateyama Seaside Hotel
21,Samarai,PG,78.12,light rain,-10.62,150.67,Nuli Sapi

In [18]:
# 8a. Create the output File (CSV)

# 6.2.7 Create a DataFrame of City Weather Data
# Export the City_Data into a CSV.
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
new_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in new_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = new_hotel_df[["Lat", "Lng"]]

In [20]:
len(locations)

325

In [21]:
len(hotel_info)

325

In [22]:
type(hotel_info)

list

In [23]:
type(locations)

pandas.core.frame.DataFrame

In [24]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#marker_layer = gmaps.marker_layer(locations, info_box_content='x')
fig.add_layer(marker_layer)

# 11b. Display the figure
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
from ipywidgets.embed import embed_minimal_html
embed_minimal_html('WeatherPy_vacation_map.html', views=[fig])