## Deliverable 3. Create a Travel Itinerary Map.

In [105]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config_g import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [106]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Avarua,CK,71.60,overcast clouds,-21.21,-159.78,Paradise Inn
1,4,Atuona,PF,79.48,few clouds,-9.80,-139.03,Villa Enata
2,6,Sochi,RU,77.00,light rain,43.60,39.73,Bounty Hotel
3,7,Bethel,US,75.99,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
4,10,Kapaa,US,78.80,few clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach

In [107]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [108]:
locations = vacation_df[["Lat", "Lng"]]

# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig1 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#marker_layer = gmaps.marker_layer(locations, info_box_content='x')
fig1.add_layer(marker_layer)

# 4b. Display the figure
# Call the figure to plot the data.
fig1

Figure(layout=FigureLayout(height='420px'))

In [109]:
# Choose 4 cities
#1
#Hotel Name : Holiday Inn Express & Suites Elk Grove Central - Hwy 99
#City : Laguna  
#Country : US
#Current Description : clear sky 
#Max Temp : 82.0 °F

#2
#Hotel Name : Hyatt Regency San Francisco Airport
#City : Hillsborough   
#Country : US
#Current Description : scattered clouds
#Max Temp : 75.0 °F

#3
#Hotel Name : Best Western Plus Garden Court Inn
#City : Fremont
#Country : US
#Current Description : clear sky
#Max Temp : 77.0 °F

#4
#Hotel Name : The Westin San Jose
#City : San Jose
#Country : US
#Current Description : smoke
#Max Temp : 80.01 °F

In [110]:
vacation_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Avarua,CK,71.60,overcast clouds,-21.21,-159.78,Paradise Inn
1,4,Atuona,PF,79.48,few clouds,-9.80,-139.03,Villa Enata
2,6,Sochi,RU,77.00,light rain,43.60,39.73,Bounty Hotel
3,7,Bethel,US,75.99,clear sky,41.37,-73.41,Courtyard by Marriott Danbury
4,10,Kapaa,US,78.80,few clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
5,12,Naliya,IN,83.07,clear sky,23.27,68.83,Hotel Panchvati
6,13,Dawlatabad,AF,74.46,clear sky,36.41,64.91,WASIM ASGAR KHAN
7,15,Gisenyi,RW,71.80,broken clouds,-1.70,29.26,Palm garden Resort
8,20,Tateyama,JP,80.01,light rain,34.98,139.87,Tateyama Seaside Hotel
9,21,Samarai,PG,78.12,light rain,-10.62,150.67,Nuli Sapi

In [111]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['Hotel Name']=='Holiday Inn Express & Suites Elk Grove Central - Hwy 99')]
vacation_end = vacation_start
vacation_stop1 = vacation_df.loc[(vacation_df['Hotel Name']=='Hyatt Regency San Francisco Airport')]
vacation_stop2 = vacation_df.loc[(vacation_df['Hotel Name']=='Best Western Plus Garden Court Inn')]
vacation_stop3 = vacation_df.loc[(vacation_df['Hotel Name']=='The Westin San Jose')] 
vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
158,356,Laguna,US,82.0,clear sky,38.42,-121.42,Holiday Inn Express & Suites Elk Grove Central...

In [112]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

#subset = vacation_start[['Lat','Lng']].to_numpy()
#tuples = [tuple(x) for x in subset.to_numpy()]
#tuples


start = tuple(map(tuple,vacation_start[['Lat','Lng']].to_numpy()))
end = start
stop1 = tuple(map(tuple,vacation_stop1[['Lat','Lng']].to_numpy()))
stop2 = tuple(map(tuple,vacation_stop2[['Lat','Lng']].to_numpy()))
stop3 = tuple(map(tuple,vacation_stop3[['Lat','Lng']].to_numpy()))
#stop3 = vacation_stop3[['Lat','Lng']].to_numpy()

start  = start[0]
end = start
stop1 = stop1[0]
stop2 = stop2[0]
stop3 = stop3[0]

stop3[0]

37.34

In [114]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig2 = gmaps.figure()
vacay_route =\
     gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3],travel_mode='DRIVING')
#    gmaps.directions_layer(test0,test1, waypoints=[test2,test3,test4])
fig2.add_layer(vacay_route)
fig2

Figure(layout=FigureLayout(height='420px'))

In [115]:
from ipywidgets.embed import embed_minimal_html
embed_minimal_html('WeatherPy_travel_map.html', views=[fig2])

In [116]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,356,Laguna,US,82.00,clear sky,38.42,-121.42,Holiday Inn Express & Suites Elk Grove Central...
1,319,Hillsborough,US,75.00,scattered clouds,37.57,-122.38,Hyatt Regency San Francisco Airport
2,666,Fremont,US,77.00,clear sky,37.55,-121.99,Best Western Plus Garden Court Inn
3,361,San Jose,US,80.01,smoke,37.34,-121.89,The Westin San Jose

In [117]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [118]:
# 11a. Add a marker layer for each city to the map.

max_temp = itinerary_df["Max Temp"]
fig3 = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#vacay_route =\
#     gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3],travel_mode='DRIVING')

fig3.add_layer(marker_layer)
#fig3.add_layer(vacay_route)

# 11b. Display the figure
# Call the figure to plot the data.
fig3

Figure(layout=FigureLayout(height='420px'))

In [119]:
from ipywidgets.embed import embed_minimal_html
embed_minimal_html('WeatherPy_travel_map_markers.html', views=[fig3])